import Animations from 'open-props/src/animations';
import Sizes from 'open-props/src/sizes'
import * as OpenColors from 'open-props/src/colors'
import * as ColorsHSL from 'open-props/src/colors-hsl'
import Fonts from 'open-props/src/fonts'
import Borders from 'open-props/src/borders'
import Aspects from 'open-props/src/aspects'
import Easings from 'open-props/src/easing'
import Gradients from 'open-props/src/gradients'
import MasksEdges from 'open-props/src/masks/edges'
import MasksCorners from 'open-props/src/masks/corners'
import Shadows from 'open-props/src/shadows'
import SVG from 'open-props/src/svg'
import Zindex from 'open-props/src/zindex'